In [4]:
import numpy as np
import pandas as pd

In [18]:
df = pd.read_csv("/content/Churn.csv")

In [19]:
df.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [59]:
df.shape

(3333, 21)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

###Row Filter Mask
- Row Boolean Mask contains as many items as there are rows in the dataframe

In [21]:
row_filter_mask = df['account length'] > 100
row_filter_mask

0        True
1        True
2        True
3       False
4       False
        ...
3328     True
3329    False
3330    False
3331     True
3332    False
Name: account length, Length: 3333, dtype: bool

Column Filter Mask

- Column boolean mask contains as many items as there are columns in the dataframe

In [34]:
col_filter_mask = df.columns.str.startswith('t')
col_filter_mask

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False])

The length of the filter should match the length of the number of rows in the data frame

In [37]:
df.loc[row_filter_mask, :]

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

Applying more than one filters

In [51]:
filter1 = (df['account length'] > 100)
filter2 = (df['international plan'] == "yes")

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

## Using more than one conditions or filters
- OR condition with "|"

In [52]:
df.loc[filter1 | filter2, :]

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3323,IN,117,415,362-5899,no,no,0,118.4,126,20.13,...,97,21.19,227.0,56,10.22,13.6,3,3.67,5,True
3324,WV,159,415,377-1164,no,no,0,169.8,114,28.87,...,105,16.80,193.7,82,8.72,11.6,4,3.13,1,False
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

AND condition with "&"

In [53]:
df.loc[filter1 & filter2, :]

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
9,WV,141,415,330-8173,yes,yes,37,258.6,84,43.96,...,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
38,AK,136,415,402-1381,yes,yes,33,203.9,106,34.66,...,99,15.95,101.7,107,4.58,10.5,6,2.84,3,False
41,MD,135,408,383-6029,yes,yes,41,173.1,85,29.43,...,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,WV,117,510,344-5766,yes,no,0,198.4,121,33.73,...,104,21.21,162.8,115,7.33,10.5,5,2.84,1,False
3291,MI,119,510,335-7324,yes,yes,22,172.1,119,29.26,...,133,19.01,150.0,94,6.75,13.9,20,3.75,1,True
3317,SD,163,415,379-7290,yes,no,0,197.2,90,33.52,...,113,16.02,211.1,94,9.50,7.8,8,2.11,1,False
3320,GA,122,510,411-5677,yes,no,0,140.0,101,23.80,...,77,16.69,120.1,133,5.40,9.7,4,2.62,4,True
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False

In [54]:
df.loc[filter1 & filter2, col_filter_mask]

,total day minutes,total day calls,total day charge,total eve minutes,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge
5,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70
7,157.0,79,26.69,103.1,94,8.76,211.8,96,9.53,7.1,6,1.92
9,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02
38,203.9,106,34.66,187.6,99,15.95,101.7,107,4.58,10.5,6,2.84
41,173.1,85,29.43,203.9,107,17.33,122.2,78,5.50,14.6,15,3.94
...,...,...,...,...,...,...,...,...,...,...,...,...
3269,198.4,121,33.73,249.5,104,21.21,162.8,115,7.33,10.5,5,2.84
3291,172.1,119,29.26,223.6,133,19.01,150.0,94,6.75,13.9,20,3.75
3317,197.2,90,33.52,188.5,113,16.02,211.1,94,9.50,7.8,8,2.11
3320,140.0,101,23.80,196.4,77,16.69,120.1,133,5.40,9.7,4,2.62
3331,213.8,105,36.35,159.6,84,13.57,139.2,137,6.26,5.0,10,1.35

- Filtering using "where". Instead of dropping the non-eligible rows, it replaces the values with NANs.
- Displays NANs for those rows which don't satisfy the condition

- You can either drop these rows or replace NANs with some other value

In [57]:
df.where(filter1 & filter2)

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3331,CT,184.0,510.0,364-6381,yes,no,0.0,213.8,105.0,36.35,...,84.0,13.57,139.2,137.0,6.26,5.0,10.0,1.35,2.0,False
3332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.where(filter1 & filter2).dropna()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
5,AL,118.0,510.0,391-8027,yes,no,0.0,223.4,98.0,37.98,...,101.0,18.75,203.9,118.0,9.18,6.3,6.0,1.70,0.0,False
7,MO,147.0,415.0,329-9001,yes,no,0.0,157.0,79.0,26.69,...,94.0,8.76,211.8,96.0,9.53,7.1,6.0,1.92,0.0,False
9,WV,141.0,415.0,330-8173,yes,yes,37.0,258.6,84.0,43.96,...,111.0,18.87,326.4,97.0,14.69,11.2,5.0,3.02,0.0,False
38,AK,136.0,415.0,402-1381,yes,yes,33.0,203.9,106.0,34.66,...,99.0,15.95,101.7,107.0,4.58,10.5,6.0,2.84,3.0,False
41,MD,135.0,408.0,383-6029,yes,yes,41.0,173.1,85.0,29.43,...,107.0,17.33,122.2,78.0,5.50,14.6,15.0,3.94,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,WV,117.0,510.0,344-5766,yes,no,0.0,198.4,121.0,33.73,...,104.0,21.21,162.8,115.0,7.33,10.5,5.0,2.84,1.0,False
3291,MI,119.0,510.0,335-7324,yes,yes,22.0,172.1,119.0,29.26,...,133.0,19.01,150.0,94.0,6.75,13.9,20.0,3.75,1.0,True
3317,SD,163.0,415.0,379-7290,yes,no,0.0,197.2,90.0,33.52,...,113.0,16.02,211.1,94.0,9.50,7.8,8.0,2.11,1.0,False
3320,GA,122.0,510.0,411-5677,yes,no,0.0,140.0,101.0,23.80,...,77.0,16.69,120.1,133.0,5.40,9.7,4.0,2.62,4.0,True
3331,CT,184.0,510.0,364-6381,yes,no,0.0,213.8,105.0,36.35,...,84.0,13.57,139.2,137.0,6.26,5.0,10.0,1.35,2.0,False

In [63]:
%%time
df.where(filter1 & filter2).fillna(0, axis=0)

CPU times: user 15 ms, sys: 0 ns, total: 15 ms
Wall time: 17.2 ms

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
1,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
2,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
3,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
4,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
3329,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
3330,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0
3331,CT,184.0,510.0,364-6381,yes,no,0.0,213.8,105.0,36.35,...,84.0,13.57,139.2,137.0,6.26,5.0,10.0,1.35,2.0,False
3332,0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.00,...,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0