In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv("/content/imdb-top-1000.csv")

In [4]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [8]:
genre_grp = movies.groupby('Genre')

In [9]:
most_pop_dirs = genre_grp['Director'].apply(lambda x: x.mode())
most_pop_dirs

Genre
Action     0    Christopher Nolan
           1     Steven Spielberg
Adventure  0          John Huston
           1      Robert Zemeckis
           2      Stanley Kubrick
Animation  0       Hayao Miyazaki
Biography  0      Martin Scorsese
Comedy     0          Woody Allen
Crime      0     Alfred Hitchcock
Drama      0       Ingmar Bergman
Family     0           Mel Stuart
           1     Steven Spielberg
Fantasy    0          F.W. Murnau
           1         Robert Wiene
Film-Noir  0     Alfred Hitchcock
           1           Carol Reed
           2          John Huston
Horror     0       John Carpenter
Mystery    0     Alfred Hitchcock
Thriller   0        Terence Young
Western    0         Sergio Leone
Name: Director, dtype: object

In [10]:
import pandas as pd

# Create a Series with empty strings
data = [1, 2, '', 4, '', 6]
empty_string_series = pd.Series(data)

# Display the series
print(empty_string_series.isnull())

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [11]:
import pandas as pd
import numpy as np

# Define DataFrame dimensions
num_rows = 5
num_cols = 3

# Create a DataFrame with random data
df = pd.DataFrame(np.random.randint(0, 10, size=(num_rows, num_cols)), columns=['A', 'B', 'C'])

# Introduce empty strings randomly
for col in df.columns:
    df.loc[df.sample(frac=0.2).index, col] = ''  # Replace 20% of values with empty strings

# Display the DataFrame
print(df)

   A  B  C
0  4  6  5
1        6
2  3  4  0
3  7  2  2
4  7  3

<ipython-input-11-7d37507a0630>:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df.sample(frac=0.2).index, col] = ''  # Replace 20% of values with empty strings
<ipython-input-11-7d37507a0630>:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df.sample(frac=0.2).index, col] = ''  # Replace 20% of values with empty strings
<ipython-input-11-7d37507a0630>:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df.sample(frac=0.2).index, col] = ''  # Replace 20% of values with empty strings

In [12]:
df.applymap(lambda x: (x=='')).sum(axis=1)

<ipython-input-12-372e486bda18>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: (x=='')).sum(axis=1)

0    0
1    2
2    0
3    0
4    1
dtype: int64

In [13]:
df.apply(lambda x: (x=='').sum(), axis=1)

0    0
1    2
2    0
3    0
4    1
dtype: int64

In [14]:
df.sample(frac=0.2).index

Index([2], dtype='int64')

In [15]:
movies.isna().sum()

Series_Title       0
Released_Year      0
Runtime            0
Genre              0
IMDB_Rating        0
Director           0
Star1              0
No_of_Votes        0
Gross              0
Metascore        157
dtype: int64

In [16]:
# For each genre the number of movies made by each director
grp = movies.groupby(['Genre', 'Director'])
num_each_dir = grp.count()
# num_each_dir.loc['Action'].nlargest(10)
num_each_dir

                                Series_Title  Released_Year  Runtime  \
Genre    Director
Action   Abhishek Chaubey                  1              1        1
         Aditya Dhar                       1              1        1
         Akira Kurosawa                    4              4        4
         Alejandro G. Iñárritu             1              1        1
         Andrew Davis                      1              1        1
...                                      ...            ...      ...
Mystery  Sujoy Ghosh                       1              1        1
         Terry Gilliam                     1              1        1
Thriller Terence Young                     1              1        1
Western  Clint Eastwood                    1              1        1
         Sergio Leone                      3              3        3

                                IMDB_Rating  Star1  No_of_Votes  Gross  \
Genre    Director
Action   Abhishek Chaubey                 1      1            1      1
         Aditya Dhar                      1      1            1      1
         Akira Kurosawa                   4      4            4      4
         Alejandro G. Iñárritu            1      1            1      1
         Andrew Davis                     1      1            1      1
...                                     ...    ...          ...    ...
Mystery  Sujoy Ghosh                      1      1            1      1
         Terry Gilliam                    1      1            1      1
Thriller Terence Young                    1      1            1      1
Western  Clint Eastwood                   1      1            1      1
         Sergio Leone                     3      3            3      3

                                Metascore
Genre    Director
Action   Abhishek Chaubey               0
         Aditya Dhar                    0
         Akira Kurosawa                 2
         Alejandro G. Iñárritu          1
         Andrew Davis                   1
...                                   ...
Mystery  Sujoy Ghosh                    0
         Terry Gilliam                  1
Thriller Terence Young                  1
Western  Clint Eastwood                 1
         Sergio Leone                   3

[749 rows x 8 columns]

In [17]:
# for each gener calculating the dir with max no-of-votes

max_votes = genre_grp['No_of_Votes'].transform('max')
flter = (movies['No_of_Votes'] == max_votes)
movies.loc[flter].sort_values(by='No_of_Votes', ascending=False)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
250,The Truman Show,1998,103,Comedy,8.1,Peter Weir,Jim Carrey,939631,125618201.0,90.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [18]:
# find dir with most num of movies

In [19]:
movies.shape

(1000, 10)

- My own groupby analysis

In [20]:
genre_grp = movies.groupby('Genre')

In [21]:
genre_grp.get_group('Drama').head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN

In [22]:
from collections import Counter

# From a list:
my_list = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
my_counter = Counter(my_list)

# From a string:
my_string = "This is a test string"
word_counter = Counter(my_string.split())

my_dict = {'a': 2, 'b': 3, 'c': 1}
my_d_counter = Counter(my_dict)

print(word_counter)
print(my_counter)
print(f"my_d_counter: {my_d_counter}")
print(f"most_common: {my_d_counter.most_common(3)}")

Counter({'This': 1, 'is': 1, 'a': 1, 'test': 1, 'string': 1})
Counter({4: 4, 3: 3, 2: 2, 1: 1})
my_d_counter: Counter({'b': 3, 'a': 2, 'c': 1})
most_common: [('b', 3), ('a', 2), ('c', 1)]

- Getting the max IMDB rating of all the genres

In [23]:
genre_grp['IMDB_Rating'].max().sort_values(ascending=False)

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Adventure    8.6
Animation    8.6
Comedy       8.6
Horror       8.5
Mystery      8.4
Fantasy      8.1
Film-Noir    8.1
Family       7.8
Thriller     7.8
Name: IMDB_Rating, dtype: float64

In [24]:
# max runtimes of all genres
genre_grp['Runtime'].agg(['max', 'mean', 'min']).sort_values(by='max', ascending=False)

           max        mean  min
Genre
Action     321  129.046512   45
Drama      242  124.737024   64
Crime      229  126.392523   80
Adventure  228  134.111111   88
Biography  209  136.022727   93
Comedy     188  112.129032   68
Western    165  148.250000  132
Mystery    138  119.083333   96
Animation  137   99.585366   71
Horror     122  102.090909   71
Family     115  107.500000  100
Film-Noir  108  104.000000  100
Thriller   108  108.000000  108
Fantasy     94   85.000000   76

In [25]:
# max runtimes of all genres
genre_grp.agg(
    avg_runtime = ('Runtime', 'mean'),
    avg_rating = ('IMDB_Rating', 'mean'),
    avg_votes = ('No_of_Votes', 'mean')

).sort_values(by='avg_runtime', ascending=False)

           avg_runtime  avg_rating      avg_votes
Genre
Western     148.250000    8.350000  322416.250000
Biography   136.022727    7.938636  272805.045455
Adventure   134.111111    7.937500  313557.819444
Action      129.046512    7.949419  420246.581395
Crime       126.392523    8.016822  313398.271028
Drama       124.737024    7.957439  212343.612457
Mystery     119.083333    7.975000  350250.333333
Comedy      112.129032    7.901290  178195.658065
Thriller    108.000000    7.800000   27733.000000
Family      107.500000    7.800000  275610.500000
Film-Noir   104.000000    7.966667  122405.000000
Horror      102.090909    7.909091  340232.363636
Animation    99.585366    7.930488  268032.073171
Fantasy      85.000000    8.000000   73111.000000

- Fantasy genre has the highest average gross of all time.

In [26]:
genre_grp.agg({
    'Metascore': 'mean',
    'Gross': 'mean',
    'IMDB_Rating': 'mean'
}).sort_values(by=['Gross', 'Metascore', 'IMDB_Rating'], ascending=[False, False, False])

           Metascore         Gross  IMDB_Rating
Genre
Fantasy          NaN  3.913633e+08     8.000000
Family     79.000000  2.195553e+08     7.800000
Action     73.419580  1.897224e+08     7.949419
Animation  81.093333  1.784326e+08     7.930488
Adventure  78.437500  1.319017e+08     7.937500
Drama      79.701245  1.225259e+08     7.957439
Mystery    79.125000  1.047014e+08     7.975000
Comedy     78.720000  1.010572e+08     7.901290
Horror     80.000000  9.405902e+07     7.909091
Biography  76.240506  9.404952e+07     7.938636
Crime      77.080460  7.899656e+07     8.016822
Film-Noir  95.666667  4.197018e+07     7.966667
Thriller   81.000000  1.755074e+07     7.800000
Western    78.250000  1.455538e+07     8.350000

In [27]:
genre_grp.agg({
    'Metascore': 'mean',
    'Gross': 'mean',
    'IMDB_Rating': 'mean'
}).sort_values(by=['Metascore', 'IMDB_Rating'], ascending=[False, False])

           Metascore         Gross  IMDB_Rating
Genre
Film-Noir  95.666667  4.197018e+07     7.966667
Animation  81.093333  1.784326e+08     7.930488
Thriller   81.000000  1.755074e+07     7.800000
Horror     80.000000  9.405902e+07     7.909091
Drama      79.701245  1.225259e+08     7.957439
Mystery    79.125000  1.047014e+08     7.975000
Family     79.000000  2.195553e+08     7.800000
Comedy     78.720000  1.010572e+08     7.901290
Adventure  78.437500  1.319017e+08     7.937500
Western    78.250000  1.455538e+07     8.350000
Crime      77.080460  7.899656e+07     8.016822
Biography  76.240506  9.404952e+07     7.938636
Action     73.419580  1.897224e+08     7.949419
Fantasy          NaN  3.913633e+08     8.000000

In [28]:
movies['Genre'].value_counts(normalize=True)

Genre
Drama        0.289
Action       0.172
Comedy       0.155
Crime        0.107
Biography    0.088
Animation    0.082
Adventure    0.072
Mystery      0.012
Horror       0.011
Western      0.004
Film-Noir    0.003
Fantasy      0.002
Family       0.002
Thriller     0.001
Name: proportion, dtype: float64

In [29]:
# top3 genres by total earnings
genre_grp['Gross'].sum().nlargest(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [30]:
genre_grp['Gross'].sum()

Genre
Action       3.263226e+10
Adventure    9.496922e+09
Animation    1.463147e+10
Biography    8.276358e+09
Comedy       1.566387e+10
Crime        8.452632e+09
Drama        3.540997e+10
Family       4.391106e+08
Fantasy      7.827267e+08
Film-Noir    1.259105e+08
Horror       1.034649e+09
Mystery      1.256417e+09
Thriller     1.755074e+07
Western      5.822151e+07
Name: Gross, dtype: float64

In [31]:
genre_grp['IMDB_Rating'].agg(
    avg_rating = 'mean'
).nlargest(1, columns='avg_rating')

         avg_rating
Genre
Western        8.35

In [32]:
genre_grp['IMDB_Rating'].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [33]:
genre_grp['IMDB_Rating'].mean().nlargest(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

- Finding the most popular director

In [34]:
movies.groupby('Director')['No_of_Votes'].agg(
    total_votes = 'sum'
).nlargest(10, columns='total_votes')

                   total_votes
Director
Christopher Nolan     11578345
Quentin Tarantino      8123208
Steven Spielberg       7817166
David Fincher          6607859
Martin Scorsese        6513530
Peter Jackson          6148579
James Cameron          4613107
Ridley Scott           4339890
Robert Zemeckis        4055464
Stanley Kubrick        3919254

- find the highest rated movie of each genre

In [35]:
max_imdb = genre_grp.IMDB_Rating.transform('max')
movies.loc[movies['IMDB_Rating'] == max_imdb]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [36]:
#find number of movies done by each actor
actor_grp = movies.groupby('Star1')
num_movies = actor_grp['Released_Year'].count()
num_movies.sort_values(ascending=False).head(20)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
Humphrey Bogart       9
Johnny Depp           8
James Stewart         8
Christian Bale        8
Toshirô Mifune        7
Denzel Washington     7
Aamir Khan            7
Charles Chaplin       6
Cary Grant            6
Daniel Radcliffe      6
Jake Gyllenhaal       6
Tom Cruise            6
Ethan Coen            6
Paul Newman           5
Harrison Ford         5
Name: Released_Year, dtype: int64

In [37]:
movies['Released_Year'].loc[movies['Released_Year'] != 'PG'].max()

'2020'

In [38]:
movies[movies['Genre'] == 'Thriller']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [39]:
pd.Series([1, 2, 3]).to_frame()

   0
0  1
1  2
2  3

In [40]:
df = pd.DataFrame()
print(df)
for group, data in genre_grp:
  df = pd.concat([df, data.loc[data['IMDB_Rating'] == (data['IMDB_Rating'].max())]])

df

Empty DataFrame
Columns: []
Index: []

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [41]:
dff = movies.loc[movies['Genre'] == 'Action']

In [42]:
dff.loc[dff['IMDB_Rating'] == (dff['IMDB_Rating'].max())]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [43]:
dff.loc[dff['Series_Title'] == 'The Dark Knight', 'Series_Title']

2    The Dark Knight
Name: Series_Title, dtype: object

In [44]:
genre_grp['Series_Title'].apply(lambda x: x.str.startswith('A').sum())

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
Name: Series_Title, dtype: int64

In [45]:
def ranking(grp):
  print(grp)
  print(grp.rank())
  return grp.rank()

In [46]:
# find rank of each movie in the group a/c to the IMDB score
rank = genre_grp['IMDB_Rating'].apply(ranking)
rank

2      9.0
5      8.9
8      8.8
10     8.8
13     8.7
      ...
968    7.6
979    7.6
982    7.6
983    7.6
985    7.6
Name: Action, Length: 172, dtype: float64
2      172.0
5      171.0
8      169.5
10     169.5
13     167.0
       ...
968     13.0
979     13.0
982     13.0
983     13.0
985     13.0
Name: Action, Length: 172, dtype: float64
21     8.6
47     8.5
93     8.3
110    8.3
114    8.3
      ...
957    7.6
964    7.6
966    7.6
984    7.6
991    7.6
Name: Adventure, Length: 72, dtype: float64
21     72.0
47     71.0
93     68.0
110    68.0
114    68.0
       ...
957     5.0
964     5.0
966     5.0
984     5.0
991     5.0
Name: Adventure, Length: 72, dtype: float64
23     8.6
43     8.5
46     8.5
56     8.4
58     8.4
      ...
956    7.6
971    7.6
976    7.6
986    7.6
992    7.6
Name: Animation, Length: 82, dtype: float64
23     82.0
43     80.5
46     80.5
56     77.0
58     77.0
       ...
956     5.5
971     5.5
976     5.5
986     5.5
992     5.5
Name: Animation, Length: 82, dtype: float64
7      8.9
15     8.7
18     8.6
35     8.5
38     8.5
      ...
923    7.6
940    7.6
949    7.6
952    7.6
987    7.6
Name: Biography, Length: 88, dtype: float64
7      88.0
15     87.0
18     86.0
35     84.5
38     84.5
       ...
923     5.5
940     5.5
949     5.5
952     5.5
987     5.5
Name: Biography, Length: 88, dtype: float64
19     8.6
26     8.6
51     8.5
52     8.5
64     8.4
      ...
977    7.6
978    7.6
989    7.6
994    7.6
995    7.6
Name: Comedy, Length: 155, dtype: float64
19     154.5
26     154.5
51     152.5
52     152.5
64     150.0
       ...
977      9.0
978      9.0
989      9.0
994      9.0
995      9.0
Name: Comedy, Length: 155, dtype: float64
1      9.2
3      9.0
4      9.0
6      8.9
22     8.6
      ...
958    7.6
960    7.6
974    7.6
980    7.6
999    7.6
Name: Crime, Length: 107, dtype: float64
1      107.0
3      105.5
4      105.5
6      104.0
22     101.5
       ...
958      7.0
960      7.0
974      7.0
980      7.0
999      7.0
Name: Crime, Length: 107, dtype: float64
0      9.3
9      8.8
11     8.8
17     8.7
20     8.6
      ...
990    7.6
993    7.6
996    7.6
997    7.6
998    7.6
Name: Drama, Length: 289, dtype: float64
0      289.0
9      287.5
11     287.5
17     286.0
20     284.0
       ...
990     17.5
993     17.5
996     17.5
997     17.5
998     17.5
Name: Drama, Length: 289, dtype: float64
688    7.8
698    7.8
Name: Family, dtype: float64
688    1.5
698    1.5
Name: Family, dtype: float64
321    8.1
568    7.9
Name: Fantasy, dtype: float64
321    2.0
568    1.0
Name: Fantasy, dtype: float64
309    8.1
456    8.0
712    7.8
Name: Film-Noir, dtype: float64
309    3.0
456    2.0
712    1.0
Name: Film-Noir, dtype: float64
49     8.5
75     8.4
271    8.1
419    8.0
544    7.9
707    7.8
724    7.7
844    7.7
876    7.7
932    7.6
948    7.6
Name: Horror, dtype: float64
49     11.0
75     10.0
271     9.0
419     8.0
544     7.0
707     6.0
724     4.0
844     4.0
876     4.0
932     1.5
948     1.5
Name: Horror, dtype: float64
69     8.4
81     8.4
119    8.3
145    8.2
220    8.1
393    8.0
420    8.0
714    7.8
829    7.7
899    7.6
959    7.6
961    7.6
Name: Mystery, dtype: float64
69     11.5
81     11.5
119    10.0
145     9.0
220     8.0
393     6.5
420     6.5
714     5.0
829     4.0
899     2.0
959     2.0
961     2.0
Name: Mystery, dtype: float64
700    7.8
Name: Thriller, dtype: float64
700    1.0
Name: Thriller, dtype: float64
12     8.8
48     8.5
115    8.3
691    7.8
Name: Western, dtype: float64
12     4.0
48     3.0
115    2.0
691    1.0
Name: Western, dtype: float64

Genre
Action    2      172.0
          5      171.0
          8      169.5
          10     169.5
          13     167.0
                 ...
Thriller  700      1.0
Western   12       4.0
          48       3.0
          115      2.0
          691      1.0
Name: IMDB_Rating, Length: 1000, dtype: float64

In [47]:
movies.shape

(1000, 10)

In [48]:
a = list(genre_grp.Series_Title)

In [49]:
genre_grp.Series_Title.apply(lambda x: x.name)

Genre
Action          Action
Adventure    Adventure
Animation    Animation
Biography    Biography
Comedy          Comedy
Crime            Crime
Drama            Drama
Family          Family
Fantasy        Fantasy
Film-Noir    Film-Noir
Horror          Horror
Mystery        Mystery
Thriller      Thriller
Western        Western
Name: Series_Title, dtype: object

In [51]:
data1 = pd.Series([50, 50, 10, 60, 45, 354], index=[0, 3, 4,5, 6, 7])
rank = data1.rank(method='average')
rank

0    3.5
3    3.5
4    1.0
5    5.0
6    2.0
7    6.0
dtype: float64

- Understanding rank()

In [52]:
import pandas as pd

# Sample Data
data = {
    'Movie': ['A', 'B', 'C', 'D', 'E'],
    'Genre': ['Action', 'Action', 'Drama', 'Drama', 'Drama'],
    'IMDB_Rating': [7.5, 8.0, 9.0, 7.0, 8.5]
}

df = pd.DataFrame(data)

In [53]:
df['new'] = data1

In [54]:
df

  Movie   Genre  IMDB_Rating   new
0     A  Action          7.5  50.0
1     B  Action          8.0   NaN
2     C   Drama          9.0   NaN
3     D   Drama          7.0  50.0
4     E   Drama          8.5  10.0

In [55]:
df['hel'] = df.apply(lambda x: x[['Genre']].str.upper(), axis=1)

In [56]:
df_gen_grp = df.groupby('Genre')
df['rating_gen_ranking'] = df_gen_grp['IMDB_Rating'].rank(method='dense', ascending=False)

In [57]:
df

  Movie   Genre  IMDB_Rating   new     hel  rating_gen_ranking
0     A  Action          7.5  50.0  ACTION                 2.0
1     B  Action          8.0   NaN  ACTION                 1.0
2     C   Drama          9.0   NaN   DRAMA                 1.0
3     D   Drama          7.0  50.0   DRAMA                 3.0
4     E   Drama          8.5  10.0   DRAMA                 2.0

- ranking of each movie in a group a/c to IMDB Score

In [58]:
genre_grp.get_group('Drama')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
...,...,...,...,...,...,...,...,...,...,...
990,Giù la testa,1971,157,Drama,7.6,Sergio Leone,Rod Steiger,30144,696690.0,77.0
993,Blowup,1966,111,Drama,7.6,Michelangelo Antonioni,David Hemmings,56513,632532802.0,82.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0

In [59]:
movies['gen_rating_rank'] = genre_grp['IMDB_Rating'].rank(method='dense', ascending=False)

In [60]:
movies[movies['Genre'] == 'Comedy']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,gen_rating_rank
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0,1.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0,1.0
51,Modern Times,1936,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,217881,163245.0,96.0,2.0
52,City Lights,1931,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,167839,19181.0,99.0,2.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
977,The Naked Gun: From the Files of Police Squad!,1988,85,Comedy,7.6,David Zucker,Leslie Nielsen,152871,78756177.0,76.0,11.0
978,"Planes, Trains & Automobiles",1987,93,Comedy,7.6,John Hughes,Steve Martin,124773,49530280.0,72.0,11.0
989,The Long Goodbye,1973,112,Comedy,7.6,Robert Altman,Elliott Gould,26337,959000.0,87.0,11.0
994,A Hard Day's Night,1964,87,Comedy,7.6,Richard Lester,John Lennon,40351,13780024.0,96.0,11.0
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,11.0

- find normalized IMDB rating group wise

In [61]:
genre_grp['IMDB_Rating'].transform(lambda x: (x-x.min()) / (x.max()-x.min()))

0      1.000
1      1.000
2      1.000
3      0.875
4      0.875
       ...
995    0.000
996    0.000
997    0.000
998    0.000
999    0.000
Name: IMDB_Rating, Length: 1000, dtype: float64

In [62]:
movies['Genre'].nunique()

14

In [63]:
movies['genre_norm_ranking'] = genre_grp['IMDB_Rating'].transform(lambda x: (x-x.min()) / (x.max()-x.min()))

In [64]:
genre_grp.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [65]:
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,gen_rating_rank,genre_norm_ranking
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,1.0,1.000
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1.0,1.000
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0,1.000
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,2.0,0.875
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,2.0,0.875
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,11.0,0.000
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,14.0,0.000
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,14.0,0.000
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,14.0,0.000
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,14.0,0.000

In [66]:
# def fnc(grp):
#   print(grp.sum())
#   return grp.sum()
# genre_grp['IMDB_Rating'].transform(fnc)

In [67]:
df

  Movie   Genre  IMDB_Rating   new     hel  rating_gen_ranking
0     A  Action          7.5  50.0  ACTION                 2.0
1     B  Action          8.0   NaN  ACTION                 1.0
2     C   Drama          9.0   NaN   DRAMA                 1.0
3     D   Drama          7.0  50.0   DRAMA                 3.0
4     E   Drama          8.5  10.0   DRAMA                 2.0

In [68]:
df.loc[2, 'IMDB_Rating'] = 8.5

In [69]:
df

  Movie   Genre  IMDB_Rating   new     hel  rating_gen_ranking
0     A  Action          7.5  50.0  ACTION                 2.0
1     B  Action          8.0   NaN  ACTION                 1.0
2     C   Drama          8.5   NaN   DRAMA                 1.0
3     D   Drama          7.0  50.0   DRAMA                 3.0
4     E   Drama          8.5  10.0   DRAMA                 2.0

In [70]:
df.loc[:, ['IMDB_Rating', 'new']].idxmax(axis=1,)

0            new
1    IMDB_Rating
2    IMDB_Rating
3            new
4            new
dtype: object

In [71]:
'D' < 'E'

True

- Most grossing actor-dir duo

In [73]:
# top3 most grossing actor-dir duo

duo = movies.groupby(['Star1', 'Director'])
act_dir = duo['Gross'].sum().reset_index().sort_values('Gross', ascending=False)
act_dir.head(3)

              Star1        Director         Gross
844  Toshirô Mifune  Akira Kurosawa  2.999877e+09
439       Joe Russo   Anthony Russo  2.205039e+09
873  William Holden    Billy Wilder  1.286779e+09

- Performances of actors in different Genres(based on Metascore)

In [74]:
act_gen_df = movies.groupby(['Star1', 'Genre'])['Metascore'].mean().reset_index()
act_gen_df.loc[act_gen_df['Star1'] == 'Christian Bale']

              Star1      Genre  Metascore
153  Christian Bale     Action       73.5
154  Christian Bale  Biography       81.0
155  Christian Bale     Comedy       64.0
156  Christian Bale      Drama       63.5

In [75]:
duo['Gross'].agg(['mean', 'sum', 'max', 'min'])

                                                  mean          sum  \
Star1                Director
Aamir Khan           Ashutosh Gowariker        70147.0      70147.0
                     Farhan Akhtar            300000.0     300000.0
                     Nitesh Tiwari          12391761.0   12391761.0
                     Rajkumar Hirani         8574506.0   17149012.0
                     Rajkumar Santoshi     213351844.0  213351844.0
...                                                ...          ...
Zbigniew Zamachowski Krzysztof Kieslowski    1464625.0    1464625.0
Zooey Deschanel      Marc Webb              32391374.0   32391374.0
Çetin Tekindor       Çagan Irmak           461855363.0  461855363.0
Éric Toledano        Olivier Nakache        13182281.0   13182281.0
Ömer Faruk Sorak     Yilmaz Erdogan        200178699.0  200178699.0

                                                   max          min
Star1                Director
Aamir Khan           Ashutosh Gowariker        70147.0      70147.0
                     Farhan Akhtar            300000.0     300000.0
                     Nitesh Tiwari          12391761.0   12391761.0
                     Rajkumar Hirani        10616104.0    6532908.0
                     Rajkumar Santoshi     213351844.0  213351844.0
...                                                ...          ...
Zbigniew Zamachowski Krzysztof Kieslowski    1464625.0    1464625.0
Zooey Deschanel      Marc Webb              32391374.0   32391374.0
Çetin Tekindor       Çagan Irmak           461855363.0  461855363.0
Éric Toledano        Olivier Nakache        13182281.0   13182281.0
Ömer Faruk Sorak     Yilmaz Erdogan        200178699.0  200178699.0

[898 rows x 4 columns]

In [79]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,gen_rating_rank,genre_norm_ranking
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,1.0,1.000
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1.0,1.000
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0,1.000
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,2.0,0.875
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,2.0,0.875

In [80]:
duo.agg({
    'Gross': ['mean', 'sum'],
    'IMDB_Rating': ['mean', 'max', 'min']
}).reset_index().sort_values(by=('Gross', 'sum'), ascending=False)

               Star1              Director         Gross                \
                                                    mean           sum
844   Toshirô Mifune        Akira Kurosawa  4.285538e+08  2.999877e+09
439        Joe Russo         Anthony Russo  5.512599e+08  2.205039e+09
873   William Holden          Billy Wilder  6.433893e+08  1.286779e+09
175   Christian Bale     Christopher Nolan  3.107350e+08  1.242940e+09
506     Klaus Kinski         Werner Herzog  5.623025e+08  1.124605e+09
..               ...                   ...           ...           ...
880          Won Bin        Jeong-beom Lee  6.460000e+03  6.460000e+03
643  Paddy Considine         Shane Meadows  6.013000e+03  6.013000e+03
407       Jared Leto      Jaco Van Dormael  3.600000e+03  3.600000e+03
815    Til Schweiger           Thomas Jahn  3.296000e+03  3.296000e+03
849   Ulrich Thomsen  Anders Thomas Jensen  1.305000e+03  1.305000e+03

    IMDB_Rating
           mean  max  min
844    8.242857  8.6  8.1
439    8.075000  8.4  7.7
873    8.200000  8.4  8.0
175    8.525000  9.0  8.2
506    8.000000  8.1  7.9
..          ...  ...  ...
880    7.800000  7.8  7.8
643    7.600000  7.6  7.6
407    7.800000  7.8  7.8
815    8.000000  8.0  8.0
849    7.800000  7.8  7.8

[898 rows x 7 columns]

## Exercise

In [81]:
ipl = pd.read_csv("/content/deliveries.csv")

In [82]:
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [84]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [105]:
ipl[ipl['batsman_runs']>6]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
151652,7898,2,Chennai Super Kings,Kolkata Knight Riders,20,1,DJ Bravo,RA Jadeja,R Vinay Kumar,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
157658,7924,1,Royal Challengers Bangalore,Mumbai Indians,10,2,BB McCullum,V Kohli,HH Pandya,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
157723,7924,1,Royal Challengers Bangalore,Mumbai Indians,20,6,C de Grandhomme,UT Yadav,MJ McClenaghan,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
168302,11151,1,Mumbai Indians,Chennai Super Kings,20,4,KA Pollard,HH Pandya,DJ Bravo,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
168845,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,9,2,CA Lynn,RV Uthappa,Mohammed Siraj,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
168903,11153,2,Kolkata Knight Riders,Royal Challengers Bangalore,18,4,AD Russell,S Gill,Mohammed Siraj,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
170577,11315,2,Mumbai Indians,Kings XI Punjab,20,1,KA Pollard,A Joseph,AS Rajpoot,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
172793,11325,1,Mumbai Indians,Delhi Capitals,6,6,RG Sharma,Q de Kock,K Paul,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
174198,11330,2,Chennai Super Kings,Royal Challengers Bangalore,19,3,MS Dhoni,DJ Bravo,N Saini,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
176579,11341,1,Chennai Super Kings,Delhi Capitals,19,6,MS Dhoni,AT Rayudu,CH Morris,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN
178461,11413,1,Sunrisers Hyderabad,Delhi Capitals,20,4,Mohammad Nabi,DJ Hooda,K Paul,0,...,0,0,1,0,7,1,8,NaN,NaN,NaN

In [97]:
six = ipl[ipl['batsman_runs'] == 6]

In [104]:
six[six['extra_runs'] != 0]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2443,11,1,Kings XI Punjab,Kolkata Knight Riders,14,5,DA Miller,WP Saha,C de Grandhomme,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
5853,25,1,Sunrisers Hyderabad,Rising Pune Supergiant,15,3,DA Warner,MC Henriques,Imran Tahir,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
11616,50,1,Kings XI Punjab,Mumbai Indians,4,2,MJ Guptill,WP Saha,SL Malinga,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
11691,50,1,Kings XI Punjab,Mumbai Indians,16,1,SE Marsh,WP Saha,MJ McClenaghan,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
15401,66,1,Deccan Chargers,Delhi Daredevils,20,6,WPUJC Vaas,RP Singh,VY Mahesh,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
18537,79,2,Delhi Daredevils,Chennai Super Kings,7,3,V Sehwag,G Gambhir,Joginder Sharma,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
23170,99,2,Mumbai Indians,Kolkata Knight Riders,6,3,ST Jayasuriya,DJ Thornely,I Sharma,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
24676,106,2,Mumbai Indians,Kings XI Punjab,20,1,SD Chitnis,CRD Fernando,VRV Singh,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
25658,110,2,Chennai Super Kings,Rajasthan Royals,19,5,JA Morkel,MS Gony,MM Patel,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
29251,126,2,Kolkata Knight Riders,Rajasthan Royals,16,6,SC Ganguly,Yashpal Singh,MM Patel,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
36547,156,2,Royal Challengers Bangalore,Kolkata Knight Riders,18,6,MV Boucher,LRPL Taylor,I Sharma,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
38632,165,1,Delhi Daredevils,Rajasthan Royals,19,2,AB de Villiers,KD Karthik,MM Patel,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
40704,173,2,Royal Challengers Bangalore,Chennai Super Kings,19,1,LRPL Taylor,V Kohli,JDP Oram,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
47116,200,1,Delhi Daredevils,Kolkata Knight Riders,14,6,DA Warner,PD Collingwood,AB Agarkar,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
47770,202,2,Chennai Super Kings,Royal Challengers Bangalore,19,6,SK Raina,C Ganapathy,R Vinay Kumar,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
55967,237,1,Kochi Tuskers Kerala,Royal Challengers Bangalore,6,2,VVS Laxman,BB McCullum,A Mithun,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
58900,249,1,Deccan Chargers,Kings XI Punjab,18,2,DT Christian,MS Gony,R McLaren,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
64885,274,2,Kochi Tuskers Kerala,Delhi Daredevils,4,6,BB McCullum,M Klinger,UT Yadav,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
67014,283,2,Royal Challengers Bangalore,Kochi Tuskers Kerala,3,2,CH Gayle,TM Dilshan,P Parameswaran,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
72090,306,1,Royal Challengers Bangalore,Mumbai Indians,19,3,AB de Villiers,SS Tiwary,AN Ahmed,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
80515,341,2,Pune Warriors,Deccan Chargers,17,1,SPD Smith,M Manhas,J Theron,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
82128,348,1,Deccan Chargers,Pune Warriors,19,6,KC Sangakkara,CL White,A Nehra,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
85105,360,2,Royal Challengers Bangalore,Mumbai Indians,11,6,CH Gayle,V Kohli,PP Ojha,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
87893,372,1,Royal Challengers Bangalore,Delhi Daredevils,17,3,CH Gayle,V Kohli,UT Yadav,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
89121,377,1,Rajasthan Royals,Mumbai Indians,17,6,AL Menaria,OA Shah,RP Singh,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
92856,392,2,Royal Challengers Bangalore,Kolkata Knight Riders,16,4,CH Gayle,AB de Villiers,JH Kallis,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
93453,395,1,Mumbai Indians,Pune Warriors,17,3,RG Sharma,KA Pollard,AB Dinda,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
101675,429,1,Royal Challengers Bangalore,Kings XI Punjab,19,3,CH Gayle,V Kohli,P Awana,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
105371,444,2,Mumbai Indians,Sunrisers Hyderabad,18,5,KA Pollard,RG Sharma,A Mishra,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
115806,488,2,Royal Challengers Bangalore,Kings XI Punjab,16,3,AB de Villiers,MA Starc,L Balaji,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
116701,492,2,Rajasthan Royals,Royal Challengers Bangalore,18,6,SPD Smith,JP Faulkner,AB Dinda,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
117560,496,1,Sunrisers Hyderabad,Kings XI Punjab,19,4,NV Ojha,MC Henriques,Sandeep Sharma,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
121248,511,2,Kolkata Knight Riders,Sunrisers Hyderabad,5,3,G Gambhir,RV Uthappa,JO Holder,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
124673,525,2,Sunrisers Hyderabad,Royal Challengers Bangalore,17,8,S Dhawan,KL Rahul,AN Ahmed,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
130445,551,1,Sunrisers Hyderabad,Chennai Super Kings,3,3,DA Warner,S Dhawan,MM Sharma,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
133588,563,2,Rajasthan Royals,Chennai Super Kings,20,1,CH Morris,Ankit Sharma,DJ Bravo,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN
147909,626,1,Royal Challengers Bangalore,Kings XI Punjab,7,5,V Kohli,CH Gayle,KC Cariappa,0,...,0,0,1,0,6,1,7,NaN,NaN,NaN

In [85]:
ipl['batsman_runs'].head(10)

0    0
1    0
2    4
3    0
4    0
5    0
6    0
7    1
8    4
9    0
Name: batsman_runs, dtype: int64

In [83]:
ipl.shape

(179078, 21)

In [107]:
# batsman with most runs
bats_gr = ipl.groupby('batsman')
bats_gr['batsman_runs'].agg(
    total_runs=('sum')
).sort_values(by='total_runs', ascending=False).head(3)

           total_runs
batsman
V Kohli          5434
SK Raina         5415
RG Sharma        4914

In [108]:
# find top 10 batsmen with max no of sixes
six.groupby('batsman').agg(
    no_of_sixes = ('batsman_runs', 'count')
).sort_values(by='no_of_sixes', ascending=False).head(10)

                no_of_sixes
batsman
CH Gayle                327
AB de Villiers          214
MS Dhoni                207
SK Raina                195
RG Sharma               194
V Kohli                 191
DA Warner               181
SR Watson               177
KA Pollard              175
YK Pathan               161

In [114]:
# batsman with the most 4s and 6s in the last 5 overs
ipl['over'].max()
last_overs = ipl[(ipl['over'] > 15) & ((ipl['batsman_runs'] == 4) | (ipl['batsman_runs'] == 6))]
clutch = last_overs.groupby('batsman').agg(
    {'match_id': 'count'}
).sort_values(by='match_id', ascending=False)
clutch

                match_id
batsman
MS Dhoni             340
AB de Villiers       208
RG Sharma            208
KA Pollard           206
V Kohli              160
...                  ...
KC Cariappa            1
Shivam Sharma          1
Shoaib Malik           1
T Curran               1
KJ Abbott              1

[360 rows x 1 columns]

In [122]:
ipl.replace('Rising Pune Supergiant', 'Rising Pune Supergiants', inplace=True)

In [123]:
virat_k = ipl.loc[ipl['batsman']=='V Kohli']
virat_k.groupby('bowling_team')['batsman_runs'].sum().reset_index().sort_values('batsman_runs', ascending=False)

               bowling_team  batsman_runs
3          Delhi Daredevils           763
0       Chennai Super Kings           749
7     Kolkata Knight Riders           675
5           Kings XI Punjab           636
8            Mumbai Indians           628
12      Sunrisers Hyderabad           509
10         Rajasthan Royals           370
1           Deccan Chargers           306
4             Gujarat Lions           283
11  Rising Pune Supergiants           271
9             Pune Warriors           128
2            Delhi Capitals            66
6      Kochi Tuskers Kerala            50

In [135]:
matches = ipl.groupby(['batsman', 'match_id'])['batsman_runs'].sum()
matches.loc['V Kohli'].max()

113

In [136]:
def max_score(player):
  matches = ipl.groupby(['batsman', 'match_id'])['batsman_runs'].sum()
  return f'The maximum score of {player} is {matches.loc[player].max()}'

In [137]:
max_score('RG Sharma')

'The maximum score of RG Sharma is 109'