In [2]:
import pandas as pd
df = pd.read_csv("/content/Churn.csv")

In [3]:
df.head()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

In [18]:
df.drop_duplicates('state', keep = False)

Empty DataFrame
Columns: [state, account length, area code, phone number, international plan, voice mail plan, number vmail messages, total day minutes, total day calls, total day charge, total eve minutes, total eve calls, total eve charge, total night minutes, total night calls, total night charge, total intl minutes, total intl calls, total intl charge, customer service calls, churn]
Index: []

[0 rows x 21 columns]

In [17]:
df.drop_duplicates('state')

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,LA,117,408,335-4719,no,no,0,184.5,97,31.37,...,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
9,WV,141,415,330-8173,yes,yes,37,258.6,84,43.96,...,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
11,RI,74,415,344-9403,no,no,0,187.7,127,31.91,...,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False
12,IA,168,408,363-1107,no,no,0,128.8,96,21.90,...,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False
13,MT,95,510,394-8006,no,no,0,156.6,88,26.62,...,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
16,ID,85,408,350-8884,no,yes,27,196.4,139,33.39,...,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False
17,VT,93,510,386-2923,no,no,0,190.7,114,32.42,...,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False
18,VA,76,510,356-2992,no,yes,33,189.7,66,32.25,...,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False
19,TX,73,415,373-2782,no,no,0,224.4,90,38.15,...,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False
20,FL,147,415,396-5800,no,no,0,155.1,117,26.37,...,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False
21,CO,77,408,393-7984,no,no,0,62.4,89,10.61,...,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
22,AZ,130,415,358-1958,no,no,0,183.0,112,31.11,...,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False
23,SC,111,415,350-2565,no,no,0,110.4,103,18.77,...,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
25,NE,174,415,331-3698,no,no,0,124.3,76,21.13,...,112,23.55,250.7,115,11.28,15.5,5,4.19,3,False
26,WY,57,408,357-3817,no,yes,39,213.0,115,36.21,...,112,16.24,182.7,115,8.22,9.5,3,2.57,0,False
29,HI,49,510,410-7789,no,no,0,119.3,117,20.28,...,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
30,IL,142,415,416-8428,no,no,0,84.8,95,14.42,...,63,11.62,250.5,148,11.27,14.2,6,3.83,2,False
31,NH,75,510,370-3359,no,no,0,226.1,105,38.44,...,107,17.13,246.2,98,11.08,10.3,5,2.78,1,False
35,GA,72,415,362-1407,no,yes,37,220.0,80,37.40,...,102,18.47,152.8,71,6.88,14.7,6,3.97,3,False
36,AK,36,408,341-9764,no,yes,30,146.3,128,24.87,...,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
41,MD,135,408,383-6029,yes,yes,41,173.1,85,29.43,...,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
42,AR,34,510,353-7289,no,no,0,124.8,82,21.22,...,98,23.99,311.5,78,14.02,10.0,4,2.70,2,False
44,WI,64,510,352-1237,no,no,0,154.0,67,26.18,...,118,19.19,265.3,86,11.94,3.5,3,0.95,1,False
45,OR,59,408,353-3061,no,yes,28,120.9,97,20.55,...,92,18.11,163.1,116,7.34,8.5,5,2.30,2,False
46,MI,65,415,363-5450,no,no,0,211.3,120,35.92,...,122,13.82,134.7,118,6.06,13.2,5,3.56,3,False
47,DE,142,408,364-1995,no,no,0,187.0,133,31.79,...,74,11.44,242.2,127,10.90,7.4,5,2.00,2,False
53,UT,96,415,404-3211,no,no,0,160.2,117,27.23,...,67,22.74,228.5,68,10.28,9.3,5,2.51,2,False
61,CA,116,415,405-3371,no,yes,34,268.6,83,45.66,...,142,15.15,166.3,106,7.48,11.6,3,3.13,2,False
62,MN,74,510,344-5117,no,yes,33,193.7,91,32.93,...,96,20.92,138.0,92,6.21,14.6,3,3.94,2,False
63,SD,149,408,332-8160,no,yes,28,180.7,92,30.72,...,64,15.96,265.5,53,11.95,12.6,3,3.40,3,False
64,NC,38,408,359-4081,no,no,0,131.2,98,22.30,...,97,13.85,159.0,106,7.15,8.2,6,2.21,2,False
65,WA,40,415,352-8305,no,yes,41,148.1,74,25.18,...,88,14.41,214.1,102,9.63,6.2,5,1.67,2,False
72,NM,147,510,415-2935,no,no,0,248.6,83,42.26,...,85,12.66,172.5,109,7.76,8.0,4,2.16,3,False
73,NV,90,415,399-4246,no,no,0,203.4,146,34.58,...,117,19.27,152.4,105,6.86,7.3,4,1.97,1,False
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True
88,KY,74,415,346-7302,no,yes,35,154.1,104,26.20,...,84,10.49,202.1,57,9.09,10.9,9,2.94,2,False
93,ME,78,415,400-9510,no,no,0,252.9,93,42.99,...,112,15.16,263.9,105,11.88,9.5,7,2.57,3,False
98,MS,120,408,355-6291,no,no,0,212.1,131,36.06,...,104,17.80,167.2,96,7.52,5.3,5,1.43,1,True
196,TN,78,415,332-6934,no,no,0,149.7,119,25.45,...,115,15.49,261.5,126,11.77,9.7,8,2.62,0,False
212,PA,82,415,333-5609,no,yes,24,155.2,131,26.38,...,106,20.78,122.4,68,5.51,10.7,3,2.89,1,False
290,CT,199,415,393-6733,no,yes,34,230.6,121,39.20,...,99,18.65,299.3,94,13.47,8.0,2,2.16,0,False
377,ND,79,408,363-3515,no,no,0,205.7,123,34.97,...,108,18.23,226.1,106,10.17,6.7,18,1.81,1,False

In [4]:
df.drop_duplicates('state', keep='first')

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
5,AL,118,510,391-8027,yes,no,0,223.4,98,37.98,...,101,18.75,203.9,118,9.18,6.3,6,1.70,0,False
6,MA,121,510,355-9993,no,yes,24,218.2,88,37.09,...,108,29.62,212.6,118,9.57,7.5,7,2.03,3,False
7,MO,147,415,329-9001,yes,no,0,157.0,79,26.69,...,94,8.76,211.8,96,9.53,7.1,6,1.92,0,False
8,LA,117,408,335-4719,no,no,0,184.5,97,31.37,...,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
9,WV,141,415,330-8173,yes,yes,37,258.6,84,43.96,...,111,18.87,326.4,97,14.69,11.2,5,3.02,0,False
10,IN,65,415,329-6603,no,no,0,129.1,137,21.95,...,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
11,RI,74,415,344-9403,no,no,0,187.7,127,31.91,...,148,13.89,196.0,94,8.82,9.1,5,2.46,0,False
12,IA,168,408,363-1107,no,no,0,128.8,96,21.90,...,71,8.92,141.1,128,6.35,11.2,2,3.02,1,False
13,MT,95,510,394-8006,no,no,0,156.6,88,26.62,...,75,21.05,192.3,115,8.65,12.3,5,3.32,3,False
15,NY,161,415,351-7269,no,no,0,332.9,67,56.59,...,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
16,ID,85,408,350-8884,no,yes,27,196.4,139,33.39,...,90,23.88,89.3,75,4.02,13.8,4,3.73,1,False
17,VT,93,510,386-2923,no,no,0,190.7,114,32.42,...,111,18.55,129.6,121,5.83,8.1,3,2.19,3,False
18,VA,76,510,356-2992,no,yes,33,189.7,66,32.25,...,65,18.09,165.7,108,7.46,10.0,5,2.70,1,False
19,TX,73,415,373-2782,no,no,0,224.4,90,38.15,...,88,13.56,192.8,74,8.68,13.0,2,3.51,1,False
20,FL,147,415,396-5800,no,no,0,155.1,117,26.37,...,93,20.37,208.8,133,9.40,10.6,4,2.86,0,False
21,CO,77,408,393-7984,no,no,0,62.4,89,10.61,...,121,14.44,209.6,64,9.43,5.7,6,1.54,5,True
22,AZ,130,415,358-1958,no,no,0,183.0,112,31.11,...,99,6.20,181.8,78,8.18,9.5,19,2.57,0,False
23,SC,111,415,350-2565,no,no,0,110.4,103,18.77,...,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
25,NE,174,415,331-3698,no,no,0,124.3,76,21.13,...,112,23.55,250.7,115,11.28,15.5,5,4.19,3,False
26,WY,57,408,357-3817,no,yes,39,213.0,115,36.21,...,112,16.24,182.7,115,8.22,9.5,3,2.57,0,False
29,HI,49,510,410-7789,no,no,0,119.3,117,20.28,...,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False
30,IL,142,415,416-8428,no,no,0,84.8,95,14.42,...,63,11.62,250.5,148,11.27,14.2,6,3.83,2,False
31,NH,75,510,370-3359,no,no,0,226.1,105,38.44,...,107,17.13,246.2,98,11.08,10.3,5,2.78,1,False
35,GA,72,415,362-1407,no,yes,37,220.0,80,37.40,...,102,18.47,152.8,71,6.88,14.7,6,3.97,3,False
36,AK,36,408,341-9764,no,yes,30,146.3,128,24.87,...,80,13.81,129.3,109,5.82,14.5,6,3.92,0,False
41,MD,135,408,383-6029,yes,yes,41,173.1,85,29.43,...,107,17.33,122.2,78,5.50,14.6,15,3.94,0,True
42,AR,34,510,353-7289,no,no,0,124.8,82,21.22,...,98,23.99,311.5,78,14.02,10.0,4,2.70,2,False
44,WI,64,510,352-1237,no,no,0,154.0,67,26.18,...,118,19.19,265.3,86,11.94,3.5,3,0.95,1,False
45,OR,59,408,353-3061,no,yes,28,120.9,97,20.55,...,92,18.11,163.1,116,7.34,8.5,5,2.30,2,False
46,MI,65,415,363-5450,no,no,0,211.3,120,35.92,...,122,13.82,134.7,118,6.06,13.2,5,3.56,3,False
47,DE,142,408,364-1995,no,no,0,187.0,133,31.79,...,74,11.44,242.2,127,10.90,7.4,5,2.00,2,False
53,UT,96,415,404-3211,no,no,0,160.2,117,27.23,...,67,22.74,228.5,68,10.28,9.3,5,2.51,2,False
61,CA,116,415,405-3371,no,yes,34,268.6,83,45.66,...,142,15.15,166.3,106,7.48,11.6,3,3.13,2,False
62,MN,74,510,344-5117,no,yes,33,193.7,91,32.93,...,96,20.92,138.0,92,6.21,14.6,3,3.94,2,False
63,SD,149,408,332-8160,no,yes,28,180.7,92,30.72,...,64,15.96,265.5,53,11.95,12.6,3,3.40,3,False
64,NC,38,408,359-4081,no,no,0,131.2,98,22.30,...,97,13.85,159.0,106,7.15,8.2,6,2.21,2,False
65,WA,40,415,352-8305,no,yes,41,148.1,74,25.18,...,88,14.41,214.1,102,9.63,6.2,5,1.67,2,False
72,NM,147,510,415-2935,no,no,0,248.6,83,42.26,...,85,12.66,172.5,109,7.76,8.0,4,2.16,3,False
73,NV,90,415,399-4246,no,no,0,203.4,146,34.58,...,117,19.27,152.4,105,6.86,7.3,4,1.97,1,False
76,DC,82,415,374-5353,no,no,0,300.3,109,51.05,...,100,15.39,270.1,73,12.15,11.7,4,3.16,0,True
88,KY,74,415,346-7302,no,yes,35,154.1,104,26.20,...,84,10.49,202.1,57,9.09,10.9,9,2.94,2,False
93,ME,78,415,400-9510,no,no,0,252.9,93,42.99,...,112,15.16,263.9,105,11.88,9.5,7,2.57,3,False
98,MS,120,408,355-6291,no,no,0,212.1,131,36.06,...,104,17.80,167.2,96,7.52,5.3,5,1.43,1,True
196,TN,78,415,332-6934,no,no,0,149.7,119,25.45,...,115,15.49,261.5,126,11.77,9.7,8,2.62,0,False
212,PA,82,415,333-5609,no,yes,24,155.2,131,26.38,...,106,20.78,122.4,68,5.51,10.7,3,2.89,1,False
290,CT,199,415,393-6733,no,yes,34,230.6,121,39.20,...,99,18.65,299.3,94,13.47,8.0,2,2.16,0,False
377,ND,79,408,363-3515,no,no,0,205.7,123,34.97,...,108,18.23,226.1,106,10.17,6.7,18,1.81,1,False

In [7]:
df.drop_duplicates(subset=('state', 'account length'), keep='last')

2       False
4       False
5       False
6       False
7       False
        ...
3328    False
3329    False
3330    False
3331    False
3332    False
Length: 2697, dtype: bool

In [10]:
df.drop_duplicates(['area code', 'international plan'], keep='last')

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
3309,VT,100,408,340-9449,yes,no,0,219.4,112,37.30,...,102,19.18,255.3,95,11.49,12.0,4,3.24,4,False
3317,SD,163,415,379-7290,yes,no,0,197.2,90,33.52,...,113,16.02,211.1,94,9.50,7.8,8,2.11,1,False
3325,OH,78,408,368-8555,no,no,0,193.4,99,32.88,...,88,9.94,243.3,109,10.95,9.3,4,2.51,2,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False

- By default it uses all the columns for identifying duplicates unless a subset is provided.
- By default , only the first occurence of the duplicates are kept.

In [11]:
df.drop_duplicates()

,state,account length,area code,phone number,international plan,voice mail plan,number vmail messages,total day minutes,total day calls,total day charge,...,total eve calls,total eve charge,total night minutes,total night calls,total night charge,total intl minutes,total intl calls,total intl charge,customer service calls,churn
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,414-4276,no,yes,36,156.2,77,26.55,...,126,18.32,279.1,83,12.56,9.9,6,2.67,2,False
3329,WV,68,415,370-3271,no,no,0,231.1,57,39.29,...,55,13.04,191.3,123,8.61,9.6,4,2.59,3,False
3330,RI,28,510,328-8230,no,no,0,180.8,109,30.74,...,58,24.55,191.9,91,8.64,14.1,6,3.81,2,False
3331,CT,184,510,364-6381,yes,no,0,213.8,105,36.35,...,84,13.57,139.2,137,6.26,5.0,10,1.35,2,False
3332,TN,74,415,400-4344,no,yes,25,234.4,113,39.85,...,82,22.60,241.4,77,10.86,13.7,4,3.70,0,False