In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/survey_results_public.csv", index_col='Respondent')
schema_df = pd.read_csv("/content/survey_results_schema.csv", index_col='Column')

In [ ]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [ ]:
schema_df.head()

                                                  QuestionText
Column
Respondent   Randomized respondent ID number (not in order ...
MainBranch   Which of the following options best describes ...
Hobbyist                               Do you code as a hobby?
OpenSourcer        How often do you contribute to open source?
OpenSource   How do you feel about the quality of open sour...

In [ ]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [ ]:
df['ConvertedComp'].value_counts()

ConvertedComp
2000000.0    709
1000000.0    558
120000.0     502
100000.0     480
150000.0     434
            ...
411096.0       1
261228.0       1
82322.0        1
66424.0        1
588012.0       1
Name: count, Length: 9162, dtype: int64

In [ ]:
df['ConvertedComp'].median()

57287.0

In [ ]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [ ]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [ ]:
df['SocialMedia']

Respondent
1          Twitter
2        Instagram
3           Reddit
4           Reddit
5         Facebook
           ...
88377      YouTube
88601          NaN
88802          NaN
88816          NaN
88863     WhatsApp
Name: SocialMedia, Length: 88883, dtype: object

In [ ]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: count, dtype: int64

In [ ]:
type(df['SocialMedia'].value_counts())

pandas.core.series.Series

In [ ]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [ ]:
df['Country'].value_counts(normalize=True)

Country
United States        0.236042
India                0.102095
Germany              0.066095
United Kingdom       0.064642
Canada               0.038253
                       ...
Tonga                0.000011
Timor-Leste          0.000011
North Korea          0.000011
Brunei Darussalam    0.000011
Chad                 0.000011
Name: proportion, Length: 179, dtype: float64

In [ ]:
country_grp = df.groupby('Country')
country_grp

In [ ]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"1,000 to 4,999 employees",NaN,1,27,1,NaN,NaN,Somewhat confident,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other(s):,Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,No,YouTube,Online,UserID,2019,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, QA or test",6,17,5,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Python;SQL;VBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apache Spark;Chef;Puppet,NaN,PyCharm;Vim,Linux-based,Development;Testing;Production;Outside of work...,Not at all,NaN,No,Yes,What?,Instagram,In real life (in person),Username,2018,A few times per month or weekly,Find answers to specific questions,Less than once per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,NaN,Data or business analyst;Student,1,18,Less than 1 year,NaN,NaN,Very confident,Not sure,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;C++;HTML/CSS;Java;JavaScript;Object...,NaN,MySQL,DynamoDB;Elasticsearch;MongoDB,Android;AWS;Google Cloud Platform;WordPress,IBM Cloud or Watson,Laravel,Angular/Angular.js;Laravel;Vue.js,NaN,Node.js,Android Studio;Atom;IntelliJ;Komodo;NetBeans;N...,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,No,Yes,What?,Twitter,Online,UserID,2012,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end;Devel...",12,25,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python;Swift;TypeScript,HTML/CSS;Java;JavaScript,MongoDB;Redis;SQLite,MongoDB;Redis,NaN,NaN,Angular/Angular.js;Express;jQuery;React.js;Oth...,Express;React.js;Other(s):,Node.js,Node.js,IntelliJ;Notepad++;Visual Studio Code;Xcode,Windows,NaN,NaN,NaN,Yes,"Fortunately, someone else has that title",What?,LinkedIn,NaN,NaN,2011,A few times per month or weekly,Find answers to specific questions;Contribute ...,Less than once per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",100 to 499 employees,Academic researcher;Educator,5,15,NaN,NaN,NaN,Somewhat confident,No,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript,C++;Python,MySQL,NaN,Other(s):,Other(s):,NaN,NaN,NaN,NaN,Notepad++,Linux-based,I do not use containers,NaN,NaN,No,Also Yes,What?,I don't use social media,Online,Username,2014,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,NaN,"No, I knew that Stack Overflow had a job board...",Yes,"Yes, somewhat",Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [ ]:
filt = (df['Country'] == 'India')
df[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [ ]:
country_grp['SocialMedia'].value_counts(normalize=True)['China']

SocialMedia
WeChat 微信                   0.670549
YouTube                     0.088186
Weibo 新浪微博                  0.069884
I don't use social media    0.044925
Twitter                     0.044925
Reddit                      0.019967
LinkedIn                    0.018303
Facebook                    0.013311
Instagram                   0.011647
Youku Tudou 优酷              0.011647
WhatsApp                    0.004992
VK ВКонта́кте               0.001664
Name: proportion, dtype: float64

In [ ]:
df['SocialMedia'].mode()

0    Reddit
Name: SocialMedia, dtype: object

In [ ]:
country_grp['ConvertedComp'].median().loc['India']

10080.0

In [ ]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [ ]:
## one not so good way
filt = (df['LanguageWorkedWith'].str.contains('Python'))
filt.fillna(False, inplace=True)
df.loc[filt]['LanguageWorkedWith']

<ipython-input-95-3af978c302ae>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filt.fillna(False, inplace=True)

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
84539    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
85738      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
86566      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
87739             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88212                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object

In [ ]:
## good way
filt = (df['Country'] == 'India')
df[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [ ]:
## this will give an error
# country_grp['LanguageWorkedWith'].str.contains('Python')

Below are the 2 different ways sum()  is used with an apply() function

In [ ]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

What % of people from each country know Python?

In [ ]:
# my solutio doesnt exactly do what the question asks to be done
ct = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
(ct / ct.sum()).sort_values(ascending=False)

Country
United States     0.276679
India             0.085202
Germany           0.067256
United Kingdom    0.065417
Canada            0.042752
                    ...
Malawi            0.000000
Tonga             0.000000
Djibouti          0.000000
Liberia           0.000000
Cape Verde        0.000000
Name: LanguageWorkedWith, Length: 179, dtype: float64

In [ ]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum()).loc['India']

3105

In [ ]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python'))

Country      Respondent
Afghanistan  722             NaN
             6417          False
             7085          False
             7353          False
             8149          False
                           ...
Zimbabwe     76594         False
             77533         False
             82752         False
             83850         False
             84155         False
Name: LanguageWorkedWith, Length: 88751, dtype: object

Practice

In [ ]:
population = pd.Series(data=[100, 200, 300, 400, 500, 234], index=['India', 'Japan', 'China', 'United States', 'Nepal', 'Australia'], name='Population')
population

India            100
Japan            200
China            300
United States    400
Nepal            500
Australia        234
Name: Population, dtype: int64

In [ ]:
knows_python = pd.Series(data=[10, 50, 172, 38, 112, 234], index=[ 'United States', 'Nepal', 'China', 'India', 'Japan', 'North Korea'], name='knowsPython')
knows_python

United States     10
Nepal             50
China            172
India             38
Japan            112
North Korea      234
Name: knowsPython, dtype: int64

In [ ]:
python_df = pd.concat([population, knows_python], axis='columns', join='inner')
python_df

               Population  knowsPython
India                 100           38
Japan                 200          112
China                 300          172
United States         400           10
Nepal                 500           50

In [ ]:
python_df['per_knows_python'] = (python_df['knowsPython']/python_df['Population']) * 100
python_df

               Population  knowsPython  per_knows_python
India                 100           38         38.000000
Japan                 200          112         56.000000
China                 300          172         57.333333
United States         400           10          2.500000
Nepal                 500           50         10.000000

- doing the same as above for our original df

In [ ]:
# the right solution and the right way
num_people_each_country = country_grp['Res']

KeyError: 'Column not found: Res'

In [ ]:
s = pd.Series([1, 23, 343, 4, 5])

In [ ]:
pd.concat([knows_python, s], axis=1)

In [ ]:
import pandas as pd
import numpy as np

# Example DataFrame
data = {
    'A': [1, np.nan, 3],
    'B': [4, np.nan, np.nan],
    'C': [7, 8, np.nan]
}
df = pd.DataFrame(data,)
print("Original DataFrame:")
print(df)

In [ ]:
df.fillna(0, axis=0)

In [ ]:
# Filling NaN with a column-specific value
filled_axis_0 = df.fillna({'A': 10, 'B': 20, 'C': 30})
print("\nFilled DataFrame with axis=0 (column-wise):")
print(filled_axis_0)

In [ ]:
# Proof for axis=0
print("\nProof for axis=0 (column-wise):")
print(df.fillna({'A': 10, 'B': 20, 'C': 30}))

In [ ]:
filled_row_ffill = df.fillna(method='ffill')
filled_row_ffill

In [ ]:
filled_row_ffill = df.fillna(method='ffill', axis=1)

In [ ]:
country_respondents = df['Country'].value_counts()
country_respondents

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [ ]:
num_people_know_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
num_people_know_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [ ]:
python_df = pd.concat([country_respondents, num_people_know_python], axis='columns')
python_df

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [ ]:
python_df.rename(columns={'count': 'total_people', 'LanguageWorkedWith': 'num_know_python'}, inplace=True)

In [ ]:
python_df

                   total_people  num_know_python
Country
United States             20949            10083
India                      9061             3105
Germany                    5866             2451
United Kingdom             5737             2384
Canada                     3395             1558
...                         ...              ...
Tonga                         1                0
Timor-Leste                   1                1
North Korea                   1                0
Brunei Darussalam             1                0
Chad                          1                0

[179 rows x 2 columns]

In [ ]:
python_df['per_know_python'] = (python_df['num_know_python'] / python_df['total_people']) * 100
python_df

                   total_people  num_know_python  per_know_python
Country
United States             20949            10083        48.131176
India                      9061             3105        34.267741
Germany                    5866             2451        41.783157
United Kingdom             5737             2384        41.554820
Canada                     3395             1558        45.891016
...                         ...              ...              ...
Tonga                         1                0         0.000000
Timor-Leste                   1                1       100.000000
North Korea                   1                0         0.000000
Brunei Darussalam             1                0         0.000000
Chad                          1                0         0.000000

[179 rows x 3 columns]

In [ ]:
python_df.sort_values(by='per_know_python', ascending=False, inplace=True)

In [ ]:
python_df.head(15)

                           total_people  num_know_python  per_know_python
Country
Sao Tome and Principe                 1                1       100.000000
Timor-Leste                           1                1       100.000000
Dominica                              1                1       100.000000
Niger                                 1                1       100.000000
Turkmenistan                          7                6        85.714286
Mauritania                            7                5        71.428571
Guinea                                3                2        66.666667
Bahamas                               3                2        66.666667
Guyana                                3                2        66.666667
Uganda                               72               47        65.277778
Iceland                              49               30        61.224490
Haiti                                 5                3        60.000000
Benin                                 5                3        60.000000
Namibia                               5                3        60.000000
Congo, Republic of the...             7                4        57.142857

In [ ]:
python_df.loc['Japan']

total_people       391.000000
num_know_python    182.000000
per_know_python     46.547315
Name: Japan, dtype: float64